services:
  app:
    build: 
      context: ..
      dockerfile: Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "8080:8080"
    volumes:
      - ../:/opt/apps/app
    networks:
    - app
  database:
    image: "mysql/mysql-server:8.0"
    ports:
        - "33306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_ROOT_HOST: "%"
        MYSQL_DATABASE: "bookstore"
        MYSQL_USER: "user"
        MYSQL_PASSWORD: "password"
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
        - ../mysql/data:/var/lib/mysql
    networks:
        - app
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-ppassword"]
        retries: 3
        timeout: 5s
networks:
    app:
        driver: bridge